### ISSUE TITLE
Headers doesn's work

### ISSUE THREAD

**Issue by mouuii** [caicloud/aloe#56]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind feature

**What happened**:
```summary: "Try get a user info by header token"
flow:
- description: "Get user info in info.yaml"
  request:
    api: GET /user
    headers:
      "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1NjY0NTgxNjAsImlzcyI6IkRpMjMwOXNsa2Q5OGE5OGFkaWFzZGxmMDlzZGdka2YyMWtqZ3Nka2YiLCJ1aWQiOjEwMDAwMDd9.Xff-abmUDYejaGMKI5r1gBEUSeLYu5ARboAAcjoEZ2g"
  response:
    statusCode: 200
```
**What you expected to happen**:
> statusCode:200 
![](http://odwokv7zi.bkt.clouddn.com/Screen%20Shot%202019-09-09%20at%209.50.31%20PM.png)

**Acture result**
>statusCode:400

**Anything else we need to know?**:
Is my headers set right or not?

**Comment by mouuii** [comment]
@liubog2008

**Comment by liubog2008** [comment]
@mouuii Thanks, I'll try to test it today

**Comment by mouuii** [comment]
https://github.com/caicloud/aloe/pull/57
